CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(255),
                       status VARCHAR(255),
                       created_at TIMESTAMP(6),

                       CONSTRAINT users_role_check
                           CHECK (role IN ('USER', 'AGENT', 'ADMIN')),

                       CONSTRAINT users_status_check
                           CHECK (status IN ('ACTIVE', 'BLOCKED'))
);

CREATE TABLE tickets (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         title VARCHAR(255) NOT NULL,
                         description VARCHAR(5000) NOT NULL,
                         status VARCHAR(255) NOT NULL,
                         priority VARCHAR(255) NOT NULL,
                         category VARCHAR(255) NOT NULL DEFAULT 'OTHER',

                         created_at TIMESTAMP(6) NOT NULL,
                         updated_at TIMESTAMP(6) NOT NULL,

                         first_response_deadline TIMESTAMP(6),
                         resolution_deadline TIMESTAMP(6),
                         first_responded_at TIMESTAMP(6),
                         resolved_at TIMESTAMP(6),

                         sla_breached BOOLEAN NOT NULL DEFAULT FALSE,

                         created_by_id BIGINT NOT NULL,
                         assigned_to_id BIGINT,

                         CONSTRAINT tickets_status_check
                             CHECK (status IN ('NEW', 'OPEN', 'IN_PROGRESS', 'WAITING', 'RESOLVED', 'CLOSED')),

                         CONSTRAINT tickets_priority_check
                             CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),

                         CONSTRAINT tickets_category_check
                             CHECK (category IN ('SOFTWARE', 'HARDWARE', 'NETWORK', 'ACCESS', 'ACCOUNT', 'OTHER')),

                         CONSTRAINT fk_tickets_created_by
                             FOREIGN KEY (created_by_id) REFERENCES users(id),

                         CONSTRAINT fk_tickets_assigned_to
                             FOREIGN KEY (assigned_to_id) REFERENCES users(id)
);

CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          message VARCHAR(3000) NOT NULL,
                          created_at TIMESTAMP(6) NOT NULL,

                          ticket_id BIGINT NOT NULL,
                          created_by_id BIGINT NOT NULL,

                          CONSTRAINT fk_comments_ticket
                              FOREIGN KEY (ticket_id) REFERENCES tickets(id),

                          CONSTRAINT fk_comments_created_by
                              FOREIGN KEY (created_by_id) REFERENCES users(id)
);

CREATE TABLE ticket_attachments (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                    original_filename VARCHAR(255) NOT NULL,
                                    stored_filename VARCHAR(255) NOT NULL UNIQUE,
                                    storage_path VARCHAR(255) NOT NULL,
                                    content_type VARCHAR(255),
                                    size_bytes BIGINT NOT NULL,
                                    created_at TIMESTAMP(6) NOT NULL,

                                    ticket_id BIGINT NOT NULL,
                                    uploaded_by_id BIGINT NOT NULL,

                                    CONSTRAINT fk_ticket_attachments_ticket
                                        FOREIGN KEY (ticket_id) REFERENCES tickets(id),

                                    CONSTRAINT fk_ticket_attachments_uploaded_by
                                        FOREIGN KEY (uploaded_by_id) REFERENCES users(id)
);

CREATE TABLE audit_logs (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            action VARCHAR(255) NOT NULL,
                            old_value VARCHAR(1000),
                            new_value VARCHAR(1000),
                            message VARCHAR(2000) NOT NULL,
                            created_at TIMESTAMP(6) NOT NULL,

                            ticket_id BIGINT NOT NULL,
                            actor_id BIGINT,

                            CONSTRAINT audit_logs_action_check
                                CHECK (action IN (
                                    'TICKET_CREATED',
                                    'STATUS_CHANGED',
                                    'TICKET_ASSIGNED',
                                    'COMMENT_ADDED',
                                    'ATTACHMENT_UPLOADED',
                                    'TICKET_RESOLVED',
                                    'TICKET_REOPENED',
                                    'TICKET_CLOSED',
                                    'SLA_BREACHED',
                                    'USER_BLOCKED',
                                    'USER_ROLE_CHANGED'
                                    )),

    CONSTRAINT fk_audit_logs_ticket
        FOREIGN KEY (ticket_id) REFERENCES tickets(id),

    CONSTRAINT fk_audit_logs_actor
        FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE INDEX idx_tickets_created_by_id ON tickets(created_by_id);
CREATE INDEX idx_tickets_assigned_to_id ON tickets(assigned_to_id);
CREATE INDEX idx_tickets_status ON tickets(status);
CREATE INDEX idx_tickets_priority ON tickets(priority);
CREATE INDEX idx_tickets_sla_breached ON tickets(sla_breached);

CREATE INDEX idx_comments_ticket_id ON comments(ticket_id);
CREATE INDEX idx_comments_created_by_id ON comments(created_by_id);

CREATE INDEX idx_ticket_attachments_ticket_id ON ticket_attachments(ticket_id);
CREATE INDEX idx_ticket_attachments_uploaded_by_id ON ticket_attachments(uploaded_by_id);

CREATE INDEX idx_audit_logs_ticket_id ON audit_logs(ticket_id);
CREATE INDEX idx_audit_logs_actor_id ON audit_logs(actor_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);